blank_issues_enabled: false
contact_links:
  - name: ğŸ¤” Feature Requests & Questions
    url: https://github.com/tiny-frontend/tiny-client-react/discussions
    about: Please ask and answer questions here.
